[package]
name = "worker-dangling-state-reproduction"
version = "0.1.0"
authors = ["Jakub Wieczorek <jakub@grafbase.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.0.9"

[profile.release]
opt-level = "s"
